### ISSUE TITLE
Choose a different license

### ISSUE THREAD

**Issue by EmreTech** [eZaR-Bot/eZaR-Website#2]
In the README, the user is suggested to not touch the website, especially the credits. If this is the case, then why is the license set as MIT? With the MIT License, according to my understanding of it, anyone can do anything with it.

**Comment by toolifelesstocode** [comment]
The website entirely needs a revamp, so most things are outdated because we most likely did not know much about this stuff. However yes, **for now,** the license has changed to Apache License, but many things shall change just after the revamp. Thank you though!

**Comment by ooliver1** [comment]
> The website entirely needs a revamp, so most things are outdated because we most likely did not know much about this stuff. However yes, **for now,** the license has changed to Apache License, but many things shall change just after the revamp. Thank you though!

You will want to update the README too

**Comment by toolifelesstocode** [comment]
> > The website entirely needs a revamp, so most things are outdated because we most likely did not know much about this stuff. However yes, **for now,** the license has changed to Apache License, but many things shall change just after the revamp. Thank you though!
> 
> You will want to update the README too

Fixed on https://github.com/eZaR-Bot/eZaR-Website/commit/c82e9dc86e6eb4ec7f8f9d9358a5091d390b4a17 Thanks!
